pg-kong:
    image: "postgres:9.4"
    environment:
        POSTGRES_USER: kong
        POSTGRES_DB: kong
pg-konga:
    image: "postgres:9.4"
    environment:
        POSTGRES_USER: konga
        POSTGRES_DB: konga
kong:
    image: kong:latest
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    volumes:
          - ./custom_plugins/basic-auth-trans:/usr/local/share/lua/5.1/kong/plugins/basic-auth-trans
          - ./kong_defaults.lua:/usr/local/share/lua/5.1/kong/templates/kong_defaults.lua
    links:
      - "pg-kong"
    environment:
      KONG_DATABASE : postgres
      KONG_CASSANDRA_CONTACT_POINTS : pg-kong
      KONG_PG_HOST : pg-kong
konga:
    image: pantsel/konga
    ports:
      - "1337:1337"
    links:
      - "kong"
      - "pg-konga"
    environment:
      NODE_ENV : development
      DB_ADAPTER: postgres
      DB_HOST: pg-konga
      DB_USER: konga
      DB_PASSWORD: konga
      DB_DATABASE: konga
